jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
jwtpassword:
  source: ENC(foTHOXMs3+XPmFWjU982ZSZl/HmV971ViWri+mqf/+s/EQ8cCb/0uNoIMOnIv52H/BI8X4+EIQojuAeuXCXB/7gzCKMj8Z6dOpR9asKKEOY=)
spring:
  server-url:
    base: http://localhost:8080
  mvc:
    path match:
      matching-strategy: ant_path_matcher #????????? ???? ???? ???
      #    jsp??
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    username: mymvc_user
    password: seven
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /mvc-docs.html
  version: 1.0.0